server:
  port: 31001
spring:
  application:
    name: pyy-framework-service-manage-cms

  freemarker:
    cache: false #关闭模板缓存
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便 进行模板测试
  servlet:
    multipart:
      #上传一个文件最大值  默认是1MB
      max-file-size: 10MB
      #上传多个文件最大值  默认是10MB
      max-request-size: 100MB
  data:
    mongodb:
      uri:  mongodb://10.10.50.189:27017
      database: pyy_cms

  jackson:
    serialization:
      write-dates-as-timestamps: true
